# Generated by Django 3.1 on 2023-02-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
