# Generated by Django 3.1 on 2023-02-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallary',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('storage', 'storage'), ('headboard', 'headboard'), ('mattress', 'mattress')], max_length=100),
        ),
    ]
