# Generated by Django 3.1 on 2023-02-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230205_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation_category', 'variation_value')},
        ),
    ]
