# Generated by Django 3.1 on 2023-02-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230203_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='delivery',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
