# Generated by Django 3.1 on 2023-02-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='account',
            name='postcode',
        ),
    ]
